apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: app-ns
spec:
  storageClassName: standard
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
